export const PUSH_CODE_ON_CHANGE = "PUSH_CODE_ON_CHANGE";
export const PUSH_LANGUAGE_ON_CHANGE = "PUSH_LANGUAGE_ON_CHANGE";
export const JOIN_GROUP = "JOIN_GROUP";
export const PULL_CODE_ON_CHANGE = "PULL_CODE_ON_CHANGE";
export const EXECUTE_CODE = "EXECUTE_CODE";
export const EXECUTED_CODE_RESULT = "EXECUTED_CODE_RESULT";
export const EXECUTE_CODE_START = "EXECUTE_CODE_START";